gui:
  cancel: '<red><bold>Cancel'
  next-page: '<gold>Next Page'
  previous-page: '<gold>Previous Page'
  unlocked: '<green><bold> Unlocked'
  locked: '<red><bold> Locked'

  altar:
    title: '<black>Select Recipe'
  builder:
    title: '<black>Spell Builder'

    change-color: '<gold><bold>Change Spell Color'
    save: '<green><bold>Save'
    clear-name: '<red><bold>Clear'
    clear-lore:
    - '<red>Shift Click to clear current spell.'
  color:
    title: '<black>Color Selector'

    red: '<red>Red: {0}'
    green: '<green>Green: {0}'
    blue: '<blue>Blue: {0}'
    current-color: '<gold>Current Color'
    
    increase: 
      name: '<gold>Increase'
      lore: 
        - '<red>Left Click: <gold>Add 1'
        - '<red>Right Click: <gold>Add 5'
        - '<red>Shift Left Click: <gold>Add 10'
        - '<red>Shift Right Click: <gold>Add 50'
        - '<red>Middle Click: <gold>Add 100'
    decrease:
      name: '<gold>Decrease'
      lore:
        - '<red>Left Click: <gold>Remove 1'
        - '<red>Right Click: <gold>Remove 5'
        - '<red>Shift Left Click: <gold>Remove 10'
        - '<red>Shift Right Click: <gold>Remove 50'
        - '<red>Middle Click: <gold>Remove 100'